### ISSUE TITLE
failed running with sample data

### ISSUE THREAD

**Issue by marialui** [pbagos/mage#2]
Hi ,
I've been using this MAGE tool, and unfortunately, I've run into a bit of a hiccup. It seems like the tool is not working as expected, and I need help to troubleshoot the issue.
I've checked the documentation, but I'm still having trouble pinpointing the issue.
Here i attached the error i got

(base) maria@maria-VirtualBox:~/mage-master$ python mage.py -c conf.txt -o results

MAGE :: Meta-Analysis of Gene Expression

Version 1.0.4; December 2022

Copyright (C) 2021 Pantelis Bagos

Freely distributed under the GNU General Public Licence (GPLv3)

--------------------------------------------------------------------------

Preparing System Arguments

Preparing System Configuration (conf.txt)

Loading File data

['study10.txt', 'study9.txt', 'study8.txt', 'a1.txt', 'a4.txt', 'study6.txt', 'study2.txt', 'a2.txt', 'study4.txt', 'study5.txt', 'a3.txt', 'study7.txt', 'study3.txt', 'study1.txt']

Meta-analysis started

Traceback (most recent call last):

  File "/home/maria/mage-master/mage.py", line 120, in <module>

    metanalysis_df = meta_analysis.run(settings, data)

  File "/home/maria/mage-master/meta_analysis.py", line 1241, in run

    meta_analysis_df = calc_metadata(expressions_team1, expressions_team2, alpha)

  File "/home/maria/mage-master/meta_analysis.py", line 272, in calc_metadata

    main(text, settings)

  File "/home/maria/mage-master/meta_analysis.py", line 773, in main

    studies = d.getdata(stys)  # load data

  File "/home/maria/mage-master/PythonMeta/core.py", line 135, in getdata

    raise Exception(Err)

Exception: error.(no data loaded)

**Comment by gmanios** [comment]
Dear Maria,

Thank you for reaching out to us and for detailing the issue you encountered.

We have identified and addressed the problem. It appears that the conf.txt file had incorrect annotations for the groups in the demo files, which prevented the demo studies from loading properly. Please note that group labels in the conf.txt file can be defined using either numbers or letter identifiers.

To resolve this issue, please follow these steps:

1) Update Your Demo User Folder: Download the updated demo_user folder from [this link](https://github.com/pbagos/mage/files/13965345/demo_user.zip). Unzip it to the mage-master folder and delete the existing demo_user folder.

2) Update the conf.txt File: Download the new conf.txt file from [here](https://github.com/pbagos/mage/files/13965353/conf.txt) and replace your current one.

3) Execute MAGE using the following command:
python mage.py -c conf.txt -o results/

4) Ensure that you are in the directory containing mage.py when you run this command.

5) Check Requirements: Make sure that all the necessary requirements for running MAGE are met.

We have updated the repository with these changes .

You can also use our web tool version of MAGE, which is available at http://rs.dib.uth.gr:3839/MAGE/ or http://195.251.108.185:3838/MAGE/.

We hope this resolves the issue. Please do not hesitate to contact us again if you need any further assistance.

Best regards,

Georgios Manios

**Comment by gmanios** [comment]
> Hi , I've been using this MAGE tool, and unfortunately, I've run into a bit of a hiccup. It seems like the tool is not working as expected, and I need help to troubleshoot the issue. I've checked the documentation, but I'm still having trouble pinpointing the issue. Here i attached the error i got
> 
> (base) maria@maria-VirtualBox:~/mage-master$ python mage.py -c conf.txt -o results
> 
> MAGE :: Meta-Analysis of Gene Expression
> 
> Version 1.0.4; December 2022
> 
> Copyright (C) 2021 Pantelis Bagos
> 
> Freely distributed under the GNU General Public Licence (GPLv3)
> 
> Preparing System Arguments
> 
> Preparing System Configuration (conf.txt)
> 
> Loading File data
> 
> ['study10.txt', 'study9.txt', 'study8.txt', 'a1.txt', 'a4.txt', 'study6.txt', 'study2.txt', 'a2.txt', 'study4.txt', 'study5.txt', 'a3.txt', 'study7.txt', 'study3.txt', 'study1.txt']
> 
> Meta-analysis started
> 
> Traceback (most recent call last):
> 
> File "/home/maria/mage-master/mage.py", line 120, in
> 
> ```
> metanalysis_df = meta_analysis.run(settings, data)
> ```
> 
> File "/home/maria/mage-master/meta_analysis.py", line 1241, in run
> 
> ```
> meta_analysis_df = calc_metadata(expressions_team1, expressions_team2, alpha)
> ```
> 
> File "/home/maria/mage-master/meta_analysis.py", line 272, in calc_metadata
> 
> ```
> main(text, settings)
> ```
> 
> File "/home/maria/mage-master/meta_analysis.py", line 773, in main
> 
> ```
> studies = d.getdata(stys)  # load data
> ```
> 
> File "/home/maria/mage-master/PythonMeta/core.py", line 135, in getdata
> 
> ```
> raise Exception(Err)
> ```
> 
> Exception: error.(no data loaded)

**Comment by marialui** [comment]
Thank you for your prompt response. However, I managed to run the analysis on the demo user but not on my datasets. I'm attaching the new error I'm encountering.
(base) maria@maria-VirtualBox:~/mage-master$ python mage.py -c conf-prova.txt -o risultati_RRMS_prova/

MAGE :: Meta-Analysis of Gene Expression

Version 1.0.4; December 2022

Copyright (C) 2021 Pantelis Bagos

Freely distributed under the GNU General Public Licence (GPLv3)

--------------------------------------------------------------------------

Preparing System Arguments

Preparing System Configuration (conf-prova.txt)

Loading File data

['GSE146383.txt', 'GSE131282.txt']

Meta-analysis started

Traceback (most recent call last):

  File "/home/maria/mage-master/mage.py", line 120, in <module>

    metanalysis_df = meta_analysis.run(settings, data)

  File "/home/maria/mage-master/meta_analysis.py", line 1241, in run

    meta_analysis_df = calc_metadata(expressions_team1, expressions_team2, alpha)

  File "/home/maria/mage-master/meta_analysis.py", line 272, in calc_metadata

    main(text, settings)

  File "/home/maria/mage-master/meta_analysis.py", line 773, in main

    studies = d.getdata(stys)  # load data

  File "/home/maria/mage-master/PythonMeta/core.py", line 117, in getdata

    raise Exception(Err)

Exception: error.(too many studies(<200))
[conf-prova.txt](https://github.com/pbagos/mage/files/13966051/conf-prova.txt)
[GSE131282.txt](https://github.com/pbagos/mage/files/13966057/GSE131282.txt)
[GSE146383.txt](https://github.com/pbagos/mage/files/13966071/GSE146383.txt)

**Comment by gmanios** [comment]
Well, I executed your GSE studies and I got the same error, but then I realised that you have duplicate gene id rows in the GSE131282.txt file, which will be considered as separate studies. Also you have 770 rows in the  gene_symbol column with the value 'permuted_negative'. ( That's why this exception appeared : "Exception: error.(too many studies(<200))") 

For instance :
<img width="724" alt="image" src="https://github.com/pbagos/mage/assets/39456816/fc8b85cc-f9d3-41b5-addd-ab26c4aed225">

<img width="648" alt="image" src="https://github.com/pbagos/mage/assets/39456816/586b6816-a23d-46c1-8c29-3e5126558053">


In this case, you should convert the probe ids from the initial GSE studies to gene identifiers. You could use the web version of MAGE with  the Convert probes to gene IDs (GISU)  choice toggled  to 'YES', for this purpose. With the default settings and given the GSE txt files you attached, I did not encountered any issues. Of course, don't forget to define the CASE and CONTROL labels as 1 and 0, respectively.

Please, do not hesitate to contact us again if you need any further assistance.

**Comment by marialui** [comment]
Goodmorning! i've been using your tool for a while now at the online version, but today i got some problems since i'm not able to reach the site at both the address ( http://rs.dib.uth.gr:3839/MAGE/ or http://195.251.108.185:3838/MAGE/). can you help me? thank you in advance

**Comment by gmanios** [comment]
Hello again
Visit this link : https://rs.dib.uth.gr/MAGE/

**Comment by marialui** [comment]
I'm so sorry but it doesn't work either

**Comment by gmanios** [comment]
Perhaps clearing your browser's cache will solve this...
Visit this link instead: http://195.251.108.211:3839/MAGE/

**Comment by marialui** [comment]
It perfectlyworks without brobe conversion, but does not perform the analysis if Convert probes to gene IDs (GISU) is set to 'yes'

**Comment by gmanios** [comment]
I think I fixed it. 
Try again now, please.

**Comment by marialui** [comment]
thank you, now it perfectly works! however I was wondering how does it handle missing values? Eg. If a gene expression was found in a dataset but not in the other (because of the use of a different Platform not including the probe for that specific gene) how does it use that information?
If i correctly understood it does not perform any kind of batch effect correction, does it?
thank you in advance
Maria

**Comment by gmanios** [comment]
Greetings!

Regarding the handling of missing values: For example, if you submit three GSE files and the gene you are interested in is only present in two of them, the meta-analysis will be performed on these two GSE files. If these two GSE files come from different platforms, the probe ID will be converted to your target namespace (e.g. ENTREZGENE), regardless of the platform. 

Also, MAGE does not perform any kind of batch effect correction. 

I hope our work has been helpful in your research. If you have any further questions, please do not hesitate to contact us.
